### PR TITLE
Add "smartTab" feature

### PR DESCRIPTION
**Pull request by gaffney2010**
This makes it so that when you hit tab or shift-tab, it looks for the next word with at least one blank.  And it highlights the first blank in that word.  This is the behavior on NYT, but not on Guardian.  It's gated by a flag.

To avoid repeating too much logic, I put the event emit in the logic of CfzCrosswordGrid.vue, and send the clue/cell over.  I'm not sure if this will work.

### CODE REVIEW

**Comment by rjkat** [comment]
> I'm not sure if this will work.

If you haven't tested locally please do that first next time before submitting a pull request. If you run into any issues getting your local environment set up let me know.

**Comment by gaffney2010** [comment]
How do I run locally?  Is it just a vue deployment command?  Or is there some other thing that has to be compiled?

**Comment by rjkat** [comment]
Should be as simple as running `npm install` and then `npm run develop` in the top-level folder. That will start a server at `localhost:5775` with hot reloading. Let me know if you run into issues.

If you are interested in running your own instance on the web, you can set your github repo to deploy to heroku whenever you push (pretty sure there are free plans available) https://devcenter.heroku.com/articles/github-integration

**Comment by gaffney2010** [comment]
Thank you for the info!  I will try this in a few days.  (I would do sooner, but I'm changing computers.)

**Comment by gaffney2010** [comment]
I am going to close for now, but will reopen later.

**Pull request closed without merging**
